//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmorozov/Work2/GradleDemo/AnotherJavaLibrary/src/main/java/com/badu/SampleApplication.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SampleApplication")
#ifdef RESTRICT_SampleApplication
#define INCLUDE_ALL_SampleApplication 0
#else
#define INCLUDE_ALL_SampleApplication 1
#endif
#undef RESTRICT_SampleApplication

#if !defined (BaduSampleApplication_) && (INCLUDE_ALL_SampleApplication || defined(INCLUDE_BaduSampleApplication))
#define BaduSampleApplication_

@protocol BaduSomeFactory;

@interface BaduSampleApplication : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)startWithBaduSomeFactory:(id<BaduSomeFactory>)factory;

@end

J2OBJC_EMPTY_STATIC_INIT(BaduSampleApplication)

FOUNDATION_EXPORT void BaduSampleApplication_init(BaduSampleApplication *self);

FOUNDATION_EXPORT BaduSampleApplication *new_BaduSampleApplication_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BaduSampleApplication *create_BaduSampleApplication_init(void);

FOUNDATION_EXPORT void BaduSampleApplication_startWithBaduSomeFactory_(id<BaduSomeFactory> factory);

J2OBJC_TYPE_LITERAL_HEADER(BaduSampleApplication)

@compatibility_alias ComBaduSampleApplication BaduSampleApplication;

#endif

#pragma pop_macro("INCLUDE_ALL_SampleApplication")
