//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmorozov/Work2/GradleDemo/AnotherJavaLibrary/src/main/java/com/badu/SomeFactory.java
//

#include "J2ObjC_source.h"
#include "SomeFactory.h"

@interface BaduSomeFactory : NSObject

@end

@implementation BaduSomeFactory

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(constructEchoWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "constructEcho", "LNSString;" };
  static const J2ObjcClassInfo _BaduSomeFactory = { "SomeFactory", "com.badu", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_BaduSomeFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(BaduSomeFactory)

J2OBJC_NAME_MAPPING(BaduSomeFactory, "com.badu", "Badu")
