//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmorozov/Work2/GradleDemo/AnotherJavaLibrary/src/main/java/com/badu/SomeFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SomeFactory")
#ifdef RESTRICT_SomeFactory
#define INCLUDE_ALL_SomeFactory 0
#else
#define INCLUDE_ALL_SomeFactory 1
#endif
#undef RESTRICT_SomeFactory

#if !defined (BaduSomeFactory_) && (INCLUDE_ALL_SomeFactory || defined(INCLUDE_BaduSomeFactory))
#define BaduSomeFactory_

@protocol BaduSomeFactory < JavaObject >

- (NSString *)constructEchoWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(BaduSomeFactory)

J2OBJC_TYPE_LITERAL_HEADER(BaduSomeFactory)

#define ComBaduSomeFactory BaduSomeFactory

#endif

#pragma pop_macro("INCLUDE_ALL_SomeFactory")
