//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmorozov/Work2/GradleDemo/JavaLibrary/src/main/java/com/badu/SomeUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SomeUtils")
#ifdef RESTRICT_SomeUtils
#define INCLUDE_ALL_SomeUtils 0
#else
#define INCLUDE_ALL_SomeUtils 1
#endif
#undef RESTRICT_SomeUtils

#if !defined (BaduSomeUtils_) && (INCLUDE_ALL_SomeUtils || defined(INCLUDE_BaduSomeUtils))
#define BaduSomeUtils_

@interface BaduSomeUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)echoWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(BaduSomeUtils)

FOUNDATION_EXPORT void BaduSomeUtils_init(BaduSomeUtils *self);

FOUNDATION_EXPORT BaduSomeUtils *new_BaduSomeUtils_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BaduSomeUtils *create_BaduSomeUtils_init(void);

FOUNDATION_EXPORT NSString *BaduSomeUtils_echoWithNSString_(NSString *text);

J2OBJC_TYPE_LITERAL_HEADER(BaduSomeUtils)

@compatibility_alias ComBaduSomeUtils BaduSomeUtils;

#endif

#pragma pop_macro("INCLUDE_ALL_SomeUtils")
